{
 "title": "Core-Infra",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Prometheus TSDB Series Count",
   "type": "timeseries",
   "description": "Shows how many time-series Prometheus currently has loaded into memory.\nUseful to detect high-cardinality issues (ex: exploding labels, unexpected metrics).",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (instance) (prometheus_tsdb_head_series{job=\"prometheus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prometheus Scrape Duration (p95)",
   "type": "timeseries",
   "description": "95th percentile of Prometheus target scrape interval length (modern replacement for scrape_duration_seconds). High values mean scrapes are taking longer; >1s can cause missed scrapes.",
   "gridPos": { "h": 7, "w": 10, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "avg by (instance) (\r\n  rate(prometheus_target_interval_length_seconds_sum[5m])\r\n  /\r\n  rate(prometheus_target_interval_length_seconds_count[5m])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Thanos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Thanos Sidecar Status",
   "type": "stat",
   "description": "Shows whether the Thanos Sidecar is running (1 = UP, 0 = DOWN)",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"thanos\", instance=~\".*sidecar.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Store Gateway Status",
   "type": "stat",
   "description": "Description:** Verifies if the Thanos Store Gateway is reachable",
   "gridPos": { "h": 3, "w": 7, "x": 7, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"thanos\", instance=~\".*store.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thanos Query Status",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "up{job=\"thanos\", instance=~\".*query.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Redis Commands processed",
   "type": "timeseries",
   "description": "Number of commands processed",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 18 },
   "targets": [
    { "expr": "redis_commands_processed_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis_Clients",
   "type": "timeseries",
   "description": "Number of active Redis clients",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 18 },
   "targets": [
    { "expr": "redis_connected_clients", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "gauge",
   "description": "Memory used by Redis ",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "redis_memory_used_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Redis Status",
   "type": "timeseries",
   "description": "Its show Redis status\n1 -> UP\n0 -> DOWN",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "up{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}