{
 "title": "VPS (68.168.218.84)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Containers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VPS - Containers Status",
   "type": "table",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "(time() - max_over_time(container_last_seen{job=\"vps-cadvisor\", image!=\"\"}[5m])) < bool 300\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "VPS Status ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "RAM Usage (percentage)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{job=\"vps-node\"} - node_memory_MemAvailable_bytes{job=\"vps-node\"}) \r\n- node_memory_Buffers_bytes{job=\"vps-node\"} \r\n- node_memory_Cached_bytes{job=\"vps-node\"}) \r\n/ node_memory_MemTotal_bytes{job=\"vps-node\"} * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Used %",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (\r\n  node_filesystem_free_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\", job=\"vps-node\"}\r\n  /\r\n  node_filesystem_size_bytes{mountpoint=\"/\", fstype!~\"tmpfs|overlay\", job=\"vps-node\"}\r\n* 100 )\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (percentage)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - avg(rate(node_cpu_seconds_total{mode=\"idle\", job=\"vps-node\"}[5m])) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPS Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{job=\"vps-node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load1{job=\"vps-node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load5{job=\"vps-node\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_load15{job=\"vps-node\"}",
     "legendFormat": "__auto"
    },
    { "expression": "A", "reducer": "last", "type": "reduce" },
    { "expression": "floor($U / 86400)", "reducer": "mean", "type": "math" }
   ]
  }
 ]
}